/* UI review only. No requests, credentials, persistent storage, or business writes. */
'use strict';
const app = document.querySelector('#app');
const roles = {business:'业务经办人', legal:'法务审查人', admin:'系统管理员'};
const tasks = [
  {id:'A',version:2,amount:'480,000',machine:'草稿完成',legal:'待复核',writeback:'未回写',phase:'review',note:'旧版文档 V1 · 审查 V1 已确认'},
  {id:'B',version:1,amount:'260,000',machine:'已完成',legal:'已确认',writeback:'模拟成功',phase:'confirmed',note:'文档 V1 · 审查 V1'},
  {id:'C',version:1,amount:'320,000',machine:'解析中',legal:'待复核',writeback:'未回写',phase:'processing',note:'当前尚无正式结论'},
  {id:'D',version:1,amount:'175,000',machine:'受阻',legal:'待复核',writeback:'未回写',phase:'blocked',note:'附件加密 · 需换传附件'},
];
let role='business', page='login', task=tasks[0], scene='normal', filter='all', riskFilter='all';
let selected=0, dirty=false, savedOpinion='', confirmed=false, pdfReady=false, writeback=false;
const escape = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pill=(text,kind='')=>`<span class="pill ${kind}">${text}</span>`;
const button=(text,action,primary=false)=>`<button data-action="${action}"${primary?' class="primary"':''}>${text}</button>`;
const note=text=>{document.querySelector('#notice').textContent=text;};
const phaseNames={processing:'机器处理中',review:'待法务复核',confirmed:'法务已确认',blocked:'处理受阻'};
function reset(){role='business';page='login';task=tasks[0];scene='normal';filter=riskFilter='all';selected=0;dirty=false;savedOpinion='';confirmed=pdfReady=writeback=false;render();}
function navItems(){return role==='business'?[['dashboard','任务大盘'],['intake','合同接入'],['reports','已确认报告']]:role==='legal'?[['dashboard','任务大盘'],['workbench','审查工作台'],['reports','交付与回写']]:[['dashboard','任务大盘'],['recovery','受阻恢复']];}
function login(){return `<section class="login"><div class="login-story"><div class="brand"><b>审</b><div>合同审查<small>CONTRACT REVIEW</small></div></div><h1>让每一个审查结论，<br>都能回到原文。</h1><p>从合同接入、证据定位，到法务复核与报告交付。<br>同一任务里看清来源、版本和责任。</p><small>中国大陆软件采购合同 · 合成数据演示 · 非正式法律意见</small></div><div class="login-form"><h2>登录工作空间</h2><p class="muted">本页预览登录布局，不采集真实账号或密码。</p><label>账号<input disabled placeholder="正式页面使用本地测试账号"></label><label>密码<input type="password" disabled placeholder="正式页面登录后按服务端角色显示"></label><label>预览身份<select id="login-role">${Object.entries(roles).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label>${button('进入设计预览','enter',true)}<small>正式页面的会话仅在本次页面中有效；刷新后需要重新登录。</small>${button('查看登录失败样式','login-error')}<p id="login-error" class="danger" role="alert"></p></div></section>`;}
function render(){
  document.querySelector('#notice').textContent='';
  if(page==='login'){app.innerHTML=login();return;}
  const title={dashboard:'任务大盘',intake:'合同接入',workbench:`软件采购合同 ${task.id}`,progress:`软件采购合同 ${task.id}`,reports:'报告与模拟回写',recovery:'受阻恢复'}[page];
  app.innerHTML=`<div class="shell"><aside><div class="brand"><b>审</b><div>合同审查<small>CONTRACT REVIEW</small></div></div><div class="nav-caption">工作空间</div><nav aria-label="主导航">${navItems().map(([key,label])=>`<button data-page="${key}" class="${page===key?'active':''}" ${page===key?'aria-current="page"':''}>${label}</button>`).join('')}</nav><div class="sidebar-foot"><label>切换设计预览身份<select id="role">${Object.entries(roles).map(([k,v])=>`<option value="${k}" ${role===k?'selected':''}>${v}</option>`).join('')}</select></label><small>合成数据演示版 · UI v0.5<br>身份切换仅用于设计预览</small>${button('退出预览','logout')}</div></aside><main class="workspace"><header><h1>${title}</h1>${pill(roles[role])}</header>${({dashboard,intake,workbench,progress,reports,recovery}[page])()}${stateTools()}</main></div>`;
}
function stateTools(){const options=page==='dashboard'?[['normal','正常列表'],['empty','空列表'],['loading','加载中']]:page==='workbench'?[['normal','风险可定位'],['unlocatable','无法精准定位'],['no-risk','规则未命中'],['conflict','保存版本冲突']]:page==='reports'?[['normal','PDF 生成失败'],['pending','报告生成中']]:page==='recovery'?[['normal','附件下载超时'],['encrypted','附件加密需换件']]:[];return `<div class="state-tools"><span>设计状态预览</span>${options.length?`<select id="scene" aria-label="设计状态">${options.map(([k,v])=>`<option value="${k}" ${scene===k?'selected':''}>${v}</option>`).join('')}</select>`:'<span>当前页面为合成示例</span>'}${button('查看会话失效','expired')}</div>`;}
function dashboard(){
  if(scene==='loading')return `<div class="subhead"><p>正在读取当前角色可见任务…</p></div><div aria-busy="true" aria-label="任务列表加载中">${'<div class="skeleton"></div>'.repeat(5)}</div>`;
  if(scene==='empty')return `<section class="empty"><h2>还没有合同任务</h2><p class="muted">${role==='business'?'上传合成合同，或导入固定模拟待办开始演示。':'业务提交合同后，可在这里查看进度。'}</p>${role==='business'?button('上传合成合同','intake',true):''}</section>`;
  const rows=tasks.filter(t=>(filter==='all'||t.phase===filter)&&(riskFilter==='all'||t.phase==='confirmed'));
  return `<div class="subhead"><p class="muted">${role==='business'?'本人任务的当前进度、下一步与已确认结果':role==='legal'?'核对原文与机器草稿，形成可追溯的法务意见':'查看处理状态与故障，协助恢复受阻任务'}</p><div class="actions">${role==='business'?button('导入模拟待办','intake')+button('上传合成合同','intake',true):''}</div></div><section class="overview"><div class="distribution"><div class="section-head"><h2>当前处理分布</h2><small>${role==='business'?'本人任务':'可见任务'} · 共 4 份</small></div><small>按当前文档的主阶段归类；旧版已确认结果不计入当前分布。</small><div class="segments" aria-hidden="true">${'<div class="segment"></div>'.repeat(4)}</div><div class="legend">${Object.values(phaseNames).map(v=>`<div><strong>${v}</strong><small>1 份 · 25%</small></div>`).join('')}</div></div><div class="panel"><div class="section-head"><h2>下一步</h2>${pill('1 项需处理','bad')}</div><hr><h3>软件采购合同 ${role==='legal'?'A':'D'}</h3><p class="${role==='legal'?'muted':'danger'}">${role==='legal'?'文档 V2 · 机器草稿已完成，待复核':'文档 V1 · 附件加密，解析受阻'}</p><p class="muted">${role==='legal'?'核对原文与两项演示规则风险。':role==='business'?'本人可上传修订附件，旧版仍保留。':'此类故障需要业务换传附件，不能直接重试。'}</p>${button(role==='legal'?'开始复核':'查看恢复路径',role==='legal'?'review-a':'recover-d',true)}</div></section><div class="section-head"><h2>合同明细</h2><small>共 ${rows.length} 项</small></div><div class="filters"><label>状态<select id="filter"><option value="all">全部</option>${Object.entries(phaseNames).map(([k,v])=>`<option value="${k}" ${filter===k?'selected':''}>${v}</option>`).join('')}</select></label>${role!=='admin'?`<label>正式风险<select id="risk-filter"><option value="all">全部</option><option value="high" ${riskFilter==='high'?'selected':''}>高</option></select></label>`:''}<span class="muted">列表筛选不改变上方概览口径</span></div><div class="table-wrap"><table><thead><tr><th>合同名称</th><th>申请人</th><th>业务类型</th><th>金额</th><th>创建时间</th><th>机器审查</th><th>法务复核</th><th>模拟回写</th>${role!=='admin'?'<th>当前正式等级</th>':''}</tr></thead><tbody>${rows.map(t=>`<tr><td><button class="quiet" data-task="${t.id}">软件采购合同 ${t.id}</button><small>文档 V${t.version} · ${t.note}</small></td><td>张明</td><td>${role==='admin'?'—':'软件采购'}</td><td>${role==='admin'?'—':'¥ '+t.amount}</td><td>09-25 10:32</td><td class="${t.phase==='blocked'?'danger':''}">${t.machine}</td><td>${t.legal}</td><td>${t.writeback}</td>${role!=='admin'?`<td class="danger">${t.phase==='confirmed'?'高':'—'}</td>`:''}</tr>`).join('')||`<tr><td colspan="9">没有符合筛选条件的任务，请调整筛选。</td></tr>`}</tbody></table></div><p class="footnote">名称、金额与状态均为设计示例；当前版本未确认时不显示正式等级。</p>`;
}
function strip(machine,legal,back){return `<div class="status-strip"><div><small>机器审查</small><strong>${machine}</strong></div><div><small>法务复核</small><strong>${legal}</strong></div><div><small>模拟回写</small><strong>${back}</strong></div></div>`;}
function progress(){return `<div class="subhead"><p class="muted">任务大盘 / 文档 V${task.version}</p>${button('返回任务大盘','dashboard')}</div>${strip(task.machine,task.legal,task.writeback)}<div class="notice-box ${task.phase==='blocked'?'bad':''}"><strong>${task.phase==='blocked'?'附件加密，暂时无法解析':'当前版本尚未形成法务确认结论'}</strong><br>${task.phase==='blocked'?'请换传可读取的附件。新附件将建立文档 V2，旧版记录保留。':role==='admin'?'管理员仅查看处理状态与故障，不展示合同正文和法务意见。':'你可以在此查看进度；法务确认后，才可查看该版本正式结论与报告。'}</div>${task.phase==='blocked'?button('上传修订附件（预览）','replacement',true):''}${task.id==='A'&&role==='business'?`<section class="panel"><h2>历史已确认结果</h2><p>文档 V1 · 审查 V1 ${pill('历史版本')}</p><p class="muted">此结果仅属于旧版；不代表当前文档 V2 的结论。</p>${button('查看旧版正式结果','history',true)}</section>`:''}`;}
function intake(){return `<div class="subhead"><p class="muted">接收附件后创建任务，解析与审查继续异步进行。</p></div><div class="form-grid"><section class="panel"><h2>上传合成合同</h2><label>送审部门<input id="department" value="采购部"></label><br><label>申请人<input id="applicant" value="张明"></label><div class="upload-zone"><h3>选择要送审的附件</h3><small>DOCX、PDF 或扫描图片 · 本页仅预览文件名称</small><label><input id="attachment" type="file" accept=".docx,.pdf,.png,.jpg,.jpeg,.tif,.tiff" aria-label="选择合成附件"></label></div>${button('预览提交反馈','upload',true)}<p class="muted">设计预览不读取或上传文件内容。正式页面由服务端校验格式与大小。</p></section><section class="panel"><div class="section-head"><h2>固定模拟待办</h2>${pill('模拟入口')}</div><hr><small>demo-f1-001</small><h3>软件采购合同 A · 采购申请</h3><p>申请人 张明 · 送审部门 采购部</p><p class="muted">附件 软件采购合同_F1.docx</p><div class="notice-box">模拟导入也会创建独立任务；附件下载超时仍保留任务，并显示恢复指引。</div><div class="actions">${button('预览导入成功','import',true)}${button('预览附件超时','import-timeout')}</div></section></div>`;}
const risks=[{title:'付款先于可核验收',rule:'DEMO-PAY-01',excerpt:'付款：软件到货后，甲方一次性支付全部合同价款。',advice:'建议明确可执行的验收标准，并将付款与验收节点关联。',opinion:'建议补充可执行验收条件，再确定付款节点。'}, {title:'软件使用权安排缺失',rule:'DEMO-IP-01',excerpt:'知识产权：交付软件及相关成果的全部知识产权归乙方所有，甲方不享有持续使用授权。',advice:'建议明确甲方满足合同目的所需的软件使用授权范围、期限与条件。',opinion:'建议补充持续使用授权及相应的交付义务。'}];
function workbench(){const r=risks[selected];return `<div class="subhead"><p class="muted">任务大盘 / 软件采购合同 A / 文档 V2 · 审查草稿 V1</p>${pill(confirmed?'预览已确认':'机器草稿 · 待法务确认',confirmed?'':'warn')}</div>${strip('已完成 · 可复核',confirmed?'已确认（预览）':'复核中 · 未确认','未回写')}<div class="workbench"><section><h2>合同原文与证据</h2><div class="panel document"><div class="document-bar"><strong>F1_软件采购合同.docx · 文档 V2</strong><small>内容示意 · 非 PDF</small></div><div class="paper-wrap"><article class="paper"><h2>软件采购合同</h2><p>甲方与乙方就软件采购与交付达成以下约定。</p><p>合同金额：人民币 480,000 元。<br>交付：乙方应交付软件及相关技术资料。</p><h3>付款与验收</h3>${scene==='no-risk'?'<p>付款：双方按功能清单验收合格后分期付款。</p>':scene==='unlocatable'?`<p>${risks[0].excerpt}</p>`:`<button class="anchor ${selected===0?'selected':''}" data-anchor="0" aria-label="付款条款，选中对应风险">${risks[0].excerpt}</button>`}<p class="danger" ${scene==='no-risk'?'hidden':''}>验收：双方未约定交付成果的验收标准、程序或付款前验收条件。</p><h3>知识产权</h3>${scene==='no-risk'?'<p>知识产权：甲方享有满足合同目的的持续使用授权。</p>':scene==='unlocatable'?`<p>${risks[1].excerpt}</p>`:`<button class="anchor ${selected===1?'selected':''}" data-anchor="1" aria-label="知识产权条款，选中对应风险">${risks[1].excerpt}</button>`}<small>仅演示交互方向；正式定位需使用后端同版固定预览与区域。</small></article></div></div></section><section><h2>风险与法务意见</h2><div class="panel">${scene==='no-risk'?'<h3>未发现已启用规则风险</h3><p class="muted">仅描述本轮规则结果。仍需法务核对合同全文，不表示法律安全。</p>':`<h3>机器发现 2 项企业演示规则风险</h3><small>草稿仅供复核；法律依据待法务核定。</small><hr>${risks.map((x,i)=>`<button class="risk-pick" data-risk="${i}" aria-pressed="${i===selected}">${pill('高风险','bad')}　${x.title}</button>`).join('')}<div class="risk-meta">企业演示规则 ${r.rule} · 版本 1</div><p>原文：${r.excerpt}</p>${scene==='unlocatable'?'<div class="notice-box">无法精准定位：缺少可靠页面区域。保留摘录，请对照同版原文核对。</div>':''}<div class="advice"><small>模型建议 · 草稿示例</small><br>${r.advice}</div><label>法务意见<textarea id="opinion" ${confirmed?'disabled':''}>${escape(savedOpinion||r.opinion)}</textarea></label><p id="dirty" class="muted">${dirty?'修改未保存，请先保存再确认。':confirmed?'已确认内容如需修改，正式页面将创建新草稿。':'当前意见为设计示例，尚未保存到后端。'}</p>${scene==='conflict'?'<div class="notice-box bad">版本已变化：服务端审查 V2，本次编辑基于 V1。保留你的输入，重新读取后比较，不自动覆盖。</div>':''}<div class="actions">${button('预览保存修改','save')}${button('预览确认审查','confirm',true)}</div>${confirmed?`<p>${button('查看报告与模拟回写','reports',true)}</p>`:''}`}</div></section></div>`;}
function currentReportTask(){return task.phase==='confirmed'||(task.id==='A'&&confirmed)?task:tasks[1];}
function reports(){const reportTask=currentReportTask();return `<div class="subhead"><div><p>软件采购合同 ${reportTask.id} · 文档 V${reportTask.version} · 审查 V1 ${pill('已确认版本')}</p><small>确认人 法务演示账号 · 2026-09-25 11:20 · 当前正式等级：高</small></div>${button('返回任务大盘','dashboard')}</div><div class="report-grid"><section class="panel"><div class="section-head"><h2>Markdown 报告</h2>${pill(scene==='pending'?'生成中':'已生成',scene==='pending'?'warn':'')}</div><p class="muted">与审查 V1 的确认快照一致。</p>${scene==='pending'?'<button disabled>生成中，暂不可预览</button>':button('预览报告版式','report-preview',true)}</section><section class="panel"><div class="section-head"><h2>PDF 报告</h2>${pill(scene==='pending'?'生成中':pdfReady?'已生成':'生成失败',scene==='pending'?'warn':pdfReady?'':'bad')}</div><p class="muted">${role==='legal'?'转换过程暂时失败，确认结果仍然有效。':'当前格式暂不可用，不影响已确认结论。'}</p>${scene==='pending'?'<button disabled>生成中，暂不可预览</button>':pdfReady?button('预览报告版式','report-preview',true):role==='legal'?button('预览同版重试','pdf-retry',true):'<button disabled>等待法务处理</button>'}</section></div><section class="panel spaced"><div class="section-head"><h2>模拟审批评论</h2>${pill(writeback?'模拟成功':'尚未回写',writeback?'':'warn')}</div><p>目标：demo-f1-001 · 软件采购申请</p><p class="muted">仅在本地模拟评论区保存已确认意见，不连接真实审批平台。任务首次绑定后不能改换目标。</p>${writeback?`<div class="advice">评论 ID：MOCK-PREVIEW-001<br>文档 V${reportTask.version} · 审查 V1 · 本地模拟评论设计示例</div>`:role==='legal'?button('预览模拟回写','writeback',true):'<p class="muted">由法务执行模拟回写。</p>'}</section>`;}
function recovery(){const encrypted=scene==='encrypted';return `<div class="subhead"><p class="muted">任务大盘 / 软件采购合同 ${encrypted?'D':'F6'} / 文档 V1</p>${pill('处理受阻','bad')}</div>${strip('受阻','待复核','未回写')}<div class="overview"><section class="panel"><h2>${encrypted?'附件加密，无法解析':'待办附件获取超时'}</h2><p>${encrypted?'需要业务经办人上传可读取的附件。':'附件尚未取得，任务已保留；没有正文、预览或风险结论。'}</p><div class="notice-box bad">${encrypted?'恢复动作：业务换传新附件，生成文档 V2。':'恢复动作：管理员按原文档 V1 重试下载。'}</div><p class="muted">${encrypted?'此类附件不能通过重复解析恢复。':'错误码 ATTACHMENT_FETCH_TIMEOUT · 已尝试 1 次'}</p>${encrypted?'<button disabled>此故障不支持管理员直接重试</button>':button('预览按原版本重试','retry',true)}</section><section class="panel"><h2>附件获取记录</h2><ul class="timeline"><li><strong>10:32:00 · 任务已登记</strong><small>业务经办人 · 文档 V1</small></li><li><strong>${encrypted?'10:32:01 · 附件已取得':'10:32:30 · 第 1 次下载超时'}</strong><small>${encrypted?'解析发现附件加密':'失败记录已保留，等待管理员重试'}</small></li></ul><small>仅管理员查看附件尝试历史；不显示原文及法务草稿。</small></section></div>`;}
function modal(title,body,actionLabel='知道了',callback=()=>{}){document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-content').innerHTML=body;const d=document.querySelector('#dialog');document.querySelector('#dialog-confirm').textContent=actionLabel;d.onclose=()=>{if(d.returnValue==='ok')callback();};d.showModal();}
function move(target){const next=()=>{page=target;scene='normal';dirty=false;savedOpinion='';render();};if(dirty)modal('修改尚未保存','<p>离开后，本次预览输入将丢失。你可以返回继续编辑。</p>','放弃修改并离开',next);else next();}
function openTask(id){task=tasks.find(t=>t.id===id);if(role==='admin'){page=task.phase==='blocked'?'recovery':'progress';scene=task.id==='D'?'encrypted':'normal';render();}else if(role==='legal'&&task.phase==='review'){move('workbench');}else if(task.phase==='confirmed')move('reports');else move('progress');}
app.addEventListener('change',e=>{if(e.target.id==='role'){const nextRole=e.target.value;e.target.value=role;const change=()=>{role=nextRole;page='dashboard';scene='normal';filter=riskFilter='all';dirty=false;render();};if(dirty)modal('修改尚未保存','<p>切换预览身份会放弃未保存输入。</p>','放弃并切换',change);else change();}if(e.target.id==='scene'){scene=e.target.value;render();}if(e.target.id==='filter'){filter=e.target.value;render();}if(e.target.id==='risk-filter'){riskFilter=e.target.value;render();}});
app.addEventListener('input',e=>{if(e.target.id==='opinion'){savedOpinion=e.target.value;dirty=true;document.querySelector('#dirty').textContent='修改未保存，请先保存再确认。';}});
app.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b)return;
  if(b.dataset.page){if(b.dataset.page==='workbench')task=tasks[0];move(b.dataset.page);return;}if(b.dataset.task){openTask(b.dataset.task);return;}
  if(b.dataset.risk!==undefined||b.dataset.anchor!==undefined){const change=()=>{selected=Number(b.dataset.risk??b.dataset.anchor);dirty=false;savedOpinion='';render();};if(dirty)modal('修改尚未保存','<p>切换风险前，请先保存或放弃本次修改。</p>','放弃并切换',change);else change();return;}
  const a=b.dataset.action;
  if(a==='enter'){role=document.querySelector('#login-role').value;move('dashboard');}
  else if(a==='login-error')document.querySelector('#login-error').textContent='账号或密码不正确，请核对后重试。（样式示例）';
  else if(['dashboard','intake','reports'].includes(a))move(a);
  else if(a==='logout')move('login');
  else if(a==='expired')modal('会话已失效','<p>正式页面将清除受保护内容并停止轮询，请重新登录。</p>','返回登录',()=>{dirty=false;move('login');});
  else if(a==='review-a'){task=tasks[0];move('workbench');}
  else if(a==='recover-d'){task=tasks[3];if(role==='admin'){page='recovery';scene='encrypted';render();}else move('progress');}
  else if(a==='replacement')modal('上传修订附件','<p>正式页面将要求选择新附件，按当前基础版本提交。成功后建立文档 V2，旧版证据保留。</p>');
  else if(a==='history')modal('历史正式结果 · 文档 V1 / 审查 V1','<p>正式等级：高。法务意见：补充验收条件与软件使用授权。</p><div class="notice-box">此为旧版确认结果；当前文档 V2 尚未确认，不得套用旧结论。</div>');
  else if(a==='upload'){const f=document.querySelector('#attachment').files[0];if(!f){note('请先选择一个合成附件。');return;}if(!document.querySelector('#department').value.trim()||!document.querySelector('#applicant').value.trim()){note('请填写送审部门和申请人。');return;}modal('任务已创建 · 反馈预览',`<p>${escape(f.name)}</p><p>附件解析中。已接收只代表任务已创建，不代表审查完成。本页未上传文件。</p>`);}
  else if(a==='import')modal('任务已创建 · 反馈预览','<p>已接收模拟待办。机器解析中 / 法务待复核 / 未回写。</p><p class="muted">设计预览未创建真实任务。</p>');
  else if(a==='import-timeout')modal('任务已保留 · 附件下载超时','<p>附件尚未取得。请联系管理员按文档 V1 重试，无需再次导入。</p><p class="muted">无正文、风险等级或报告。可切换管理员身份预览恢复界面。</p>');
  else if(a==='save'){if(scene==='conflict'){note('版本已变化，本次输入已保留；正式页面需重新读取并比较后提交。');return;}dirty=false;document.querySelector('#dirty').textContent='预览输入已暂存于本页，未提交后端。';note('保存反馈预览 · 正式页面保存成功后更新审查版本');}
  else if(a==='confirm'){if(dirty||scene==='conflict'){note('请先保存修改并解决版本冲突，再确认。');return;}modal('确认审查版本 · 交互预览','<p>请确认已核对同版原文、风险等级与法务意见。正式确认后，业务可查看该版本结论，并生成报告。</p>','预览确认结果',()=>{confirmed=true;render();note('仅预览确认反馈，未提交后端');});}
  else if(a==='pdf-retry'){pdfReady=true;render();note('重试成功样式 · 设计示例未生成真实 PDF');}
  else if(a==='report-preview')modal(`报告预览 · 文档 V${currentReportTask().version} / 审查 V1`,`<h3>软件采购合同 ${currentReportTask().id} · 法务确认意见</h3><p>综合等级：高</p><p>一、付款条件：补充可核验的验收标准。<br>二、知识产权：明确软件持续使用授权。</p><small>合成版式示例，不是实际生成的报告。</small>`);
  else if(a==='writeback')modal(`模拟回写 · 文档 V${currentReportTask().version} / 审查 V1`,'<p>目标 demo-f1-001 · 软件采购申请。正式操作只向本地模拟评论区写入该确认版本。</p>','预览成功状态',()=>{writeback=true;render();note('模拟成功状态预览 · 没有写入真实评论');});
  else if(a==='retry')modal('按原文档 V1 重试 · 交互预览','<p>正式操作会保留首次失败记录，新建第 2 次附件尝试；成功后继续解析，不新建任务或文档版本。</p>','预览重试反馈',()=>note('第 2 次附件获取成功 → 解析中（仅样式预览）'));
});
document.querySelector('#reset').addEventListener('click',()=>{if(dirty)modal('重置设计预览','<p>将放弃本页未保存输入，回到登录预览。</p>','重置',reset);else reset();});
render();
